# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'floatingPointDesignKfQzku.ui'
##
## Created by: Qt User Interface Compiler version 6.1.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(812, 857)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 20, 801, 791))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabConv = QWidget()
        self.tabConv.setObjectName(u"tabConv")
        self.txt_InpConv = QLineEdit(self.tabConv)
        self.txt_InpConv.setObjectName(u"txt_InpConv")
        self.txt_InpConv.setGeometry(QRect(140, 110, 391, 41))
        self.btn_Conv = QPushButton(self.tabConv)
        self.btn_Conv.setObjectName(u"btn_Conv")
        self.btn_Conv.setGeometry(QRect(560, 110, 91, 41))
        self.lbl_SlctConv = QLabel(self.tabConv)
        self.lbl_SlctConv.setObjectName(u"lbl_SlctConv")
        self.lbl_SlctConv.setGeometry(QRect(340, 20, 121, 31))
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.lbl_SlctConv.setFont(font)
        self.lbl_SlctConv.setMouseTracking(False)
        self.rad_FloatConv = QRadioButton(self.tabConv)
        self.rad_FloatConv.setObjectName(u"rad_FloatConv")
        self.rad_FloatConv.setGeometry(QRect(160, 80, 89, 20))
        self.rad_HexDConv = QRadioButton(self.tabConv)
        self.rad_HexDConv.setObjectName(u"rad_HexDConv")
        self.rad_HexDConv.setGeometry(QRect(260, 80, 89, 20))
        self.rad_BnryConv = QRadioButton(self.tabConv)
        self.rad_BnryConv.setObjectName(u"rad_BnryConv")
        self.rad_BnryConv.setGeometry(QRect(380, 80, 89, 20))
        self.lbl_FloatConv = QLabel(self.tabConv)
        self.lbl_FloatConv.setObjectName(u"lbl_FloatConv")
        self.lbl_FloatConv.setGeometry(QRect(200, 220, 101, 21))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setItalic(True)
        self.lbl_FloatConv.setFont(font1)
        self.lbl_hexDConv = QLabel(self.tabConv)
        self.lbl_hexDConv.setObjectName(u"lbl_hexDConv")
        self.lbl_hexDConv.setGeometry(QRect(200, 290, 101, 21))
        self.lbl_hexDConv.setFont(font1)
        self.lbl_bnryConv = QLabel(self.tabConv)
        self.lbl_bnryConv.setObjectName(u"lbl_bnryConv")
        self.lbl_bnryConv.setGeometry(QRect(200, 360, 101, 21))
        self.lbl_bnryConv.setFont(font1)
        self.lbl_fltSolConv = QLabel(self.tabConv)
        self.lbl_fltSolConv.setObjectName(u"lbl_fltSolConv")
        self.lbl_fltSolConv.setGeometry(QRect(330, 220, 141, 16))
        self.lbl_hexDSolConv = QLabel(self.tabConv)
        self.lbl_hexDSolConv.setObjectName(u"lbl_hexDSolConv")
        self.lbl_hexDSolConv.setGeometry(QRect(330, 290, 141, 16))
        self.lbl_bnrySolConv = QLabel(self.tabConv)
        self.lbl_bnrySolConv.setObjectName(u"lbl_bnrySolConv")
        self.lbl_bnrySolConv.setGeometry(QRect(330, 360, 141, 16))
        self.lbl_SemConv = QLabel(self.tabConv)
        self.lbl_SemConv.setObjectName(u"lbl_SemConv")
        self.lbl_SemConv.setGeometry(QRect(200, 410, 101, 21))
        self.lbl_SemConv.setFont(font1)
        self.lbl_bnrySolConv_2 = QLabel(self.tabConv)
        self.lbl_bnrySolConv_2.setObjectName(u"lbl_bnrySolConv_2")
        self.lbl_bnrySolConv_2.setGeometry(QRect(330, 410, 141, 16))
        self.rad_SemConv = QRadioButton(self.tabConv)
        self.rad_SemConv.setObjectName(u"rad_SemConv")
        self.rad_SemConv.setGeometry(QRect(470, 80, 89, 20))
        self.tabWidget.addTab(self.tabConv, "")
        self.tabCalc = QWidget()
        self.tabCalc.setObjectName(u"tabCalc")
        self.lbl_SlctCal = QLabel(self.tabCalc)
        self.lbl_SlctCal.setObjectName(u"lbl_SlctCal")
        self.lbl_SlctCal.setGeometry(QRect(340, 20, 121, 31))
        self.lbl_SlctCal.setFont(font)
        self.lbl_SlctCal.setMouseTracking(False)
        self.rad_FloatCal = QRadioButton(self.tabCalc)
        self.rad_FloatCal.setObjectName(u"rad_FloatCal")
        self.rad_FloatCal.setGeometry(QRect(160, 70, 89, 20))
        self.txt_InpCal = QLineEdit(self.tabCalc)
        self.txt_InpCal.setObjectName(u"txt_InpCal")
        self.txt_InpCal.setGeometry(QRect(140, 110, 521, 41))
        self.rad_BnryCal = QRadioButton(self.tabCalc)
        self.rad_BnryCal.setObjectName(u"rad_BnryCal")
        self.rad_BnryCal.setGeometry(QRect(440, 70, 89, 20))
        self.rad_HexDCal = QRadioButton(self.tabCalc)
        self.rad_HexDCal.setObjectName(u"rad_HexDCal")
        self.rad_HexDCal.setGeometry(QRect(290, 70, 89, 20))
        self.btn_CalOP = QPushButton(self.tabCalc)
        self.btn_CalOP.setObjectName(u"btn_CalOP")
        self.btn_CalOP.setGeometry(QRect(380, 440, 91, 41))
        self.ddl_Operator = QComboBox(self.tabCalc)
        self.ddl_Operator.addItem("")
        self.ddl_Operator.addItem("")
        self.ddl_Operator.addItem("")
        self.ddl_Operator.addItem("")
        self.ddl_Operator.addItem("")
        self.ddl_Operator.addItem("")
        self.ddl_Operator.addItem("")
        self.ddl_Operator.addItem("")
        self.ddl_Operator.addItem("")
        self.ddl_Operator.addItem("")
        self.ddl_Operator.addItem("")
        self.ddl_Operator.setObjectName(u"ddl_Operator")
        self.ddl_Operator.setGeometry(QRect(320, 220, 191, 41))
        self.lbl_SlctCalOP = QLabel(self.tabCalc)
        self.lbl_SlctCalOP.setObjectName(u"lbl_SlctCalOP")
        self.lbl_SlctCalOP.setGeometry(QRect(360, 170, 131, 31))
        self.lbl_SlctCalOP.setFont(font)
        self.lbl_SlctCalOP.setMouseTracking(False)
        self.rad_BnryCalOP = QRadioButton(self.tabCalc)
        self.rad_BnryCalOP.setObjectName(u"rad_BnryCalOP")
        self.rad_BnryCalOP.setGeometry(QRect(480, 330, 89, 20))
        self.lbl_SlctOP = QLabel(self.tabCalc)
        self.lbl_SlctOP.setObjectName(u"lbl_SlctOP")
        self.lbl_SlctOP.setGeometry(QRect(360, 280, 121, 31))
        self.lbl_SlctOP.setFont(font)
        self.lbl_SlctOP.setMouseTracking(False)
        self.rad_FloatCalOP = QRadioButton(self.tabCalc)
        self.rad_FloatCalOP.setObjectName(u"rad_FloatCalOP")
        self.rad_FloatCalOP.setGeometry(QRect(180, 330, 89, 20))
        self.rad_HexDCalOP = QRadioButton(self.tabCalc)
        self.rad_HexDCalOP.setObjectName(u"rad_HexDCalOP")
        self.rad_HexDCalOP.setGeometry(QRect(320, 330, 89, 20))
        self.txt_InpCalOP = QLineEdit(self.tabCalc)
        self.txt_InpCalOP.setObjectName(u"txt_InpCalOP")
        self.txt_InpCalOP.setGeometry(QRect(160, 370, 521, 41))
        self.lbl_fltSolOP_2 = QLabel(self.tabCalc)
        self.lbl_fltSolOP_2.setObjectName(u"lbl_fltSolOP_2")
        self.lbl_fltSolOP_2.setGeometry(QRect(420, 580, 141, 16))
        self.lbl_fltSolOP = QLabel(self.tabCalc)
        self.lbl_fltSolOP.setObjectName(u"lbl_fltSolOP")
        self.lbl_fltSolOP.setGeometry(QRect(420, 620, 141, 16))
        self.lbl_hexaDOP = QLabel(self.tabCalc)
        self.lbl_hexaDOP.setObjectName(u"lbl_hexaDOP")
        self.lbl_hexaDOP.setGeometry(QRect(290, 570, 101, 21))
        self.lbl_hexaDOP.setFont(font1)
        self.lbl_bnryOP = QLabel(self.tabCalc)
        self.lbl_bnryOP.setObjectName(u"lbl_bnryOP")
        self.lbl_bnryOP.setGeometry(QRect(290, 610, 101, 21))
        self.lbl_bnryOP.setFont(font1)
        self.lbl_fltSolOP_3 = QLabel(self.tabCalc)
        self.lbl_fltSolOP_3.setObjectName(u"lbl_fltSolOP_3")
        self.lbl_fltSolOP_3.setGeometry(QRect(420, 530, 141, 16))
        self.lbl_FloatingOP = QLabel(self.tabCalc)
        self.lbl_FloatingOP.setObjectName(u"lbl_FloatingOP")
        self.lbl_FloatingOP.setGeometry(QRect(290, 530, 101, 21))
        self.lbl_FloatingOP.setFont(font1)
        self.lbl_SemOP = QLabel(self.tabCalc)
        self.lbl_SemOP.setObjectName(u"lbl_SemOP")
        self.lbl_SemOP.setGeometry(QRect(290, 650, 101, 21))
        self.lbl_SemOP.setFont(font1)
        self.lbl_fltSolOP_4 = QLabel(self.tabCalc)
        self.lbl_fltSolOP_4.setObjectName(u"lbl_fltSolOP_4")
        self.lbl_fltSolOP_4.setGeometry(QRect(420, 660, 141, 16))
        self.rad_SemCalOP = QRadioButton(self.tabCalc)
        self.rad_SemCalOP.setObjectName(u"rad_SemCalOP")
        self.rad_SemCalOP.setGeometry(QRect(610, 330, 89, 20))
        self.rad_SemCal = QRadioButton(self.tabCalc)
        self.rad_SemCal.setObjectName(u"rad_SemCal")
        self.rad_SemCal.setGeometry(QRect(580, 70, 89, 20))
        self.tabWidget.addTab(self.tabCalc, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 812, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_Conv.setText(QCoreApplication.translate("MainWindow", u"Convert", None))
        self.lbl_SlctConv.setText(QCoreApplication.translate("MainWindow", u"Select a Operand", None))
        self.rad_FloatConv.setText(QCoreApplication.translate("MainWindow", u"Floating", None))
        self.rad_HexDConv.setText(QCoreApplication.translate("MainWindow", u"HexaDecimal", None))
        self.rad_BnryConv.setText(QCoreApplication.translate("MainWindow", u"Binary", None))
        self.lbl_FloatConv.setText(QCoreApplication.translate("MainWindow", u"Floating", None))
        self.lbl_hexDConv.setText(QCoreApplication.translate("MainWindow", u"HexaDecimal", None))
        self.lbl_bnryConv.setText(QCoreApplication.translate("MainWindow", u"Binary", None))
        self.lbl_fltSolConv.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_hexDSolConv.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_bnrySolConv.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_SemConv.setText(QCoreApplication.translate("MainWindow", u"SEM", None))
        self.lbl_bnrySolConv_2.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.rad_SemConv.setText(QCoreApplication.translate("MainWindow", u"SEM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConv), QCoreApplication.translate("MainWindow", u"Converter", None))
        self.lbl_SlctCal.setText(QCoreApplication.translate("MainWindow", u"Select a Operand", None))
        self.rad_FloatCal.setText(QCoreApplication.translate("MainWindow", u"Floating", None))
        self.rad_BnryCal.setText(QCoreApplication.translate("MainWindow", u"Binary (SEM)", None))
        self.rad_HexDCal.setText(QCoreApplication.translate("MainWindow", u"HexaDecimal", None))
        self.btn_CalOP.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.ddl_Operator.setItemText(0, QCoreApplication.translate("MainWindow", u"Add (+)", None))
        self.ddl_Operator.setItemText(1, QCoreApplication.translate("MainWindow", u"Subtract (-)", None))
        self.ddl_Operator.setItemText(2, QCoreApplication.translate("MainWindow", u"Multiply (*)", None))
        self.ddl_Operator.setItemText(3, QCoreApplication.translate("MainWindow", u"Divide (/)", None))
        self.ddl_Operator.setItemText(4, QCoreApplication.translate("MainWindow", u"AND (&&)", None))
        self.ddl_Operator.setItemText(5, QCoreApplication.translate("MainWindow", u"NOT ( ! )", None))
        self.ddl_Operator.setItemText(6, QCoreApplication.translate("MainWindow", u"OR ( || )", None))
        self.ddl_Operator.setItemText(7, QCoreApplication.translate("MainWindow", u"NOR ( ~| )", None))
        self.ddl_Operator.setItemText(8, QCoreApplication.translate("MainWindow", u"XOR (^)", None))
        self.ddl_Operator.setItemText(9, QCoreApplication.translate("MainWindow", u"SHR", None))
        self.ddl_Operator.setItemText(10, QCoreApplication.translate("MainWindow", u"SHL", None))

        self.lbl_SlctCalOP.setText(QCoreApplication.translate("MainWindow", u"Select a Operator", None))
        self.rad_BnryCalOP.setText(QCoreApplication.translate("MainWindow", u"Binary", None))
        self.lbl_SlctOP.setText(QCoreApplication.translate("MainWindow", u"Select a Operand", None))
        self.rad_FloatCalOP.setText(QCoreApplication.translate("MainWindow", u"Floating", None))
        self.rad_HexDCalOP.setText(QCoreApplication.translate("MainWindow", u"HexaDecimal", None))
        self.lbl_fltSolOP_2.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_fltSolOP.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_hexaDOP.setText(QCoreApplication.translate("MainWindow", u"HexaDecimal", None))
        self.lbl_bnryOP.setText(QCoreApplication.translate("MainWindow", u"Binary", None))
        self.lbl_fltSolOP_3.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_FloatingOP.setText(QCoreApplication.translate("MainWindow", u"Floating", None))
        self.lbl_SemOP.setText(QCoreApplication.translate("MainWindow", u"SEM", None))
        self.lbl_fltSolOP_4.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.rad_SemCalOP.setText(QCoreApplication.translate("MainWindow", u"SEM", None))
        self.rad_SemCal.setText(QCoreApplication.translate("MainWindow", u"SEM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCalc), QCoreApplication.translate("MainWindow", u"Calculator", None))
    # retranslateUi

